"""add dialogue matches

Revision ID: 225ab31e7604
Revises: 00e2d2ab6d00
Create Date: 2026-08-25 19:17:30.366217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225ab31e7604'
down_revision: Union[str, Sequence[str], None] = '00e2d2ab6d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('matched_text', sa.String(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('frame_timestamp', sa.Float(), nullable=False),
    sa.Column('frame_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialogue_matches')
    # ### end Alembic commands ###
