"""add video external id

Revision ID: b3964c142a1e
Revises: f486f9e2e271
Create Date: 2026-08-26 14:16:49.470231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3964c142a1e'
down_revision: Union[str, Sequence[str], None] = 'f486f9e2e271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('external_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'videos', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    op.drop_column('videos', 'external_id')
    # ### end Alembic commands ###
